-- Seed data for DHC Buildout Tracker
-- Stores and the master vendor list only. store_vendors is left empty on
-- purpose -- vendors are attached to a store explicitly from that store's
-- board, only when they're actually in use for that buildout.

INSERT INTO stores (id, name, address, target_open_date, status, notes) VALUES
  ('store-1516-wichita', '1516 Wichita', '2692 N Greenwich Ct', '2026-09-11', 'in-progress', NULL),
  ('store-1519-manhattan', '1519 Manhattan', '214 Leavenworth St', '2026-10-20', 'in-progress', NULL),
  ('store-wichita-4', 'Wichita #4', 'North Maize Rd', NULL, 'pre-buildout', NULL),
  ('store-lawrence', 'Lawrence', 'Iowa St', NULL, 'pre-buildout', NULL);

INSERT INTO vendors (id, company_name, contact_name, phone, email, industry) VALUES
  ('v01', 'Lingle Design', 'Carl Lingle', NULL, NULL, 'Architect'),
  ('v02', 'Avanti', 'Becca Westlake', '916-805-6379', 'bwestlake@avanticorporate.com', 'Equipment'),
  ('v03', 'Concept Services', 'Brian Morris', '512-540-1263', 'bmorris@conceptserv.com', 'Equipment'),
  ('v04', 'JBI', 'Jack Potter', '714-878-3600', 'jpotter@jbi-interiors.com', 'Millwork'),
  ('v05', 'Randal Retail', 'Sam Riddle', '816-820-0740', 'samr@randalretail.com', 'Millwork'),
  ('v06', 'PFG', 'Steve Pettingill', '503-329-1691', 'steve.pettingill@pfgc.com', 'Food'),
  ('v07', 'RTI', 'Melissa Millolt', '985-222-5368', 'mmillolt@rti-inc.com', 'Bulk Oil'),
  ('v08', 'DarPro (Eastern WA)', 'Brett Ballou', '253-948-6945', 'brett.ballou@darlingii.com', 'Bulk Oil'),
  ('v09', 'Coke', 'Will Freeman', '404-922-7764', 'DHC@coca-cola.com', 'Coke'),
  ('v10', 'Resource POS', 'Greg Gower', '704-779-7269', 'ggower@resourcepos.com', 'POS'),
  ('v11', 'QPOS', NULL, NULL, 'itteam@daveshotchicken.com', 'POS'),
  ('v12', 'Etundra', 'Jessica Miller', '303-248-0222', 'jmiller@tundrafmp.com', 'Smallwares'),
  ('v13', 'DF Supply', 'Laura O''Connell', '203-701-9272', 'loconnell@dfsupply.com', 'Smallwares'),
  ('v14', 'Wasserstrom', 'Zach Williams', '614-737-8810', 'zachwilliams@wasserstrom.com', 'Smallwares'),
  ('v15', 'Clark National Accounts', 'Morgan Buterbaugh', NULL, 'mbuterbaugh@clarknationalaccounts.com', 'Smallwares'),
  ('v16', 'Dynamic Media', 'Jamie Waldie', '586-693-1096', 'JWaldie@dm-us.com', 'Music'),
  ('v17', 'Villa Lighting', 'James Alto', '760-898-0154', 'james.alto@villalighting.com', 'Lighting'),
  ('v18', 'Villa Lighting', 'Luke Hill', '314-633-0544', 'dhc@villalighting.com', 'Lighting'),
  ('v19', 'Commercial Lighting', 'Jackson Polakov', '760-777-2007', 'dhc@commercial-lighting.net', 'Lighting'),
  ('v20', 'Patio Shoppers', 'Todd Chism', '951-500-1803', 'todd@patioshoppers.com', 'Umbrella'),
  ('v21', 'Mission Linen', 'Ray Van Broekhuizen', '951-314-1332', 'rvanbro@missionlinen.com', 'Linen'),
  ('v22', 'NUCO2', 'Rodney Husbands', '772-349-4859', 'rhusbands@nuco2.com', 'CO2'),
  ('v23', 'Silver Dipped Graphix', 'Gary Najaryan', '818-929-2828', 'info@silverdippedgraphix.com', 'Dave''s Interior Cut Outs'),
  ('v24', 'HME', 'Varies', '858-535-6000', 'Inside.Sales-Reps@hme.com', 'Drive Thru Headset'),
  ('v25', 'DSA', 'Connie Macias', '310-537-5000 ext.105', 'cmacias@dsasignage.com', 'Drive Thru Menuboards'),
  ('v26', 'Ecolab', 'Robert Allen', '336-858-0893', 'Robert.Allen@SSDCsoap.com', 'Chemicals, Dish Machine & Water Filters'),
  ('v27', 'Ecolab', 'Radames Gutierrez', '949-338-3471', 'radames.gutierrez@ecolab.com', 'EcoSure'),
  ('v28', 'Ecolab', 'Jon Bond', '702-343-3854', 'jonathan.bond@ecolab.com', 'Pest'),
  ('v29', 'Ecolab', 'Jason Archibeque', '805-220-8111', 'jason.archibeque@ecolab.com', 'Reorders & Copies of Invoices'),
  ('v30', 'Visible Graphics', 'Dave Mahn', '818-402-8801', 'dave@visiblegraphics.com', 'Exterior Signage'),
  ('v31', 'Jones Sign', 'Kevin Callihan', '920-241-6216', 'daveshotchicken@jonessign.com', 'Exterior Signage and Drive Thru Menu Boards'),
  ('v32', 'PMG (PITCO)', 'Gabriel Samano', '818-334-9095', 'gsamano@pmgnow.com', 'Fryers'),
  ('v33', 'Splatterhouse', 'Dehmq', NULL, '1@dehmq.com', 'Graffiti'),
  ('v34', 'Splatterhouse', 'Arthur Akopyan', '424-346-3333', 'splatterhaus@icloud.com', 'Graffiti'),
  ('v35', 'Schier', 'Rob Parten', '913-951-3300', 'daveshotchicken@schierproducts.com', 'Grease Interceptor'),
  ('v36', 'Captive Aire', 'Duncan Brown', '714-957-1500', 'duncan.brown@captiveaire.com', 'Hood'),
  ('v37', 'Accurex', 'Garrett Koschak', '715-297-4792', 'dhc@accurex.com', 'Hood'),
  ('v38', 'Interface', 'Justin Girimont', '314-377-3745', 'justin.girimont@interfacesys.com', 'IT - Firewall, phones, alarms, cameras'),
  ('v39', 'JTech', 'Regina Pare', NULL, 'rnouvel@jtech.com', 'Pagers'),
  ('v40', 'Roll A Shade', 'Debbie Clausen', '951-459-0279', 'Debbie.Clausen@rollashade.com', 'Shades'),
  ('v41', 'MAG Resources', 'Todd Janiga', '330-807-3809', 't.janiga@magresources.net', 'Shades'),
  ('v42', 'Taylor Freezers', 'Lee Ann Langan', '818-266-6258', 'leeann@taylorfreezers.com', 'Shake Machine'),
  ('v43', 'Silikal Flooring', 'Mark Feldman', '775-772-2797 (C)', 'mfeldman@silikalamerica.com', 'Silikal Flooring'),
  ('v44', 'Daltile', 'Dennis Hopkins', '704-576-4953', 'dennis.hopkins@daltile.com', 'Tile'),
  ('v45', 'Creative Materials Corp. (CMC)', 'Tamara Ramsey', '469-796-9389 (C)', 'daveshottile@creativematerialscorp.com', 'Tile and Wood Wainscot'),
  ('v46', 'Ubest', 'George Chen', '714-255-9299', 'george@ubestpackaging.com; DHCportalsupport@franchisescaling.com; dhccorporatesupport@franchisescaling.com', 'Uniforms/Grand Open Kit / coming Soon Banner'),
  ('v47', 'ASG', 'Jason Welch', '614-400-5493', 'jwelch@advancesigngroup.com', 'Awning (VP Client Services)'),
  ('v48', 'ASG', 'Heather Anderson', '614-984-7778', 'handerson@advancesigngroup.com', 'Awning (Project Manager)'),
  ('v49', 'Vivant Group', 'Jimmy Le', '214-732-3483', 'jimmy@vivantcorp.com', 'Internet/Phone'),
  ('v50', 'Vivant Group', 'Hamed', NULL, 'hamed@vivantcorp.com', 'Internet/Phone'),
  ('v51', 'MDC', 'Frank Abraham', '678-313-8849', 'DHCteam@mdcwall.com', 'Acoustical Sound Panels'),
  ('v52', 'Colour Tree USA', 'Victor C', '888-557-8910', 'info@colourtreeusa.com', 'Sail Exterior Shade'),
  ('v53', 'Pattison id', 'Betsy Ewart', '865-254-3568', 'bewart@pattisonid.com', 'Front Exterior Red Structure');
